### ISSUE TITLE
Any CDN service for icons?

### ISSUE THREAD

**Issue by Ehuang-design** [alexandrebouttier/coinmarketcap-icons-cryptos#1]
hi,

thank you very much for icons, is there any cdn that we can use?
for example can you add them in jsdelivr.com ?

thank you so much!

**Comment by alexandrebouttier** [comment]
Hello, thanks to you I will watch this if it is possible to make a CDN .

in the meantime you can do like this  ``` <img src="https://github.com/alexandrebouttier/coinmarketcap-icons-cryptos/blob/main/icons/btc.png?raw=true" /> ```

**Comment by Ehuang-design** [comment]
thank you :)
