### ISSUE TITLE
Adding more coins

### ISSUE THREAD

**Issue by Ehuang-design** [alexandrebouttier/coinmarketcap-icons-cryptos#2]
hi,

can you please add those coins too?:
`usdsb
erd
bchsv
bchabc
storm
rpx
ins
trig
edo
lend
gxs
arn
ven
mod
icn
iota
yoyo
bqx
hsr
foo
eur
gbp
aud
wnxm
eosup
yfidown
yfiup
sushidown
1inch`

i can provide example of icons if needed :)

**Comment by alexandrebouttier** [comment]
Hello, this repo contains only the icons listed on coinmarketcap, and their api

**Comment by Ehuang-design** [comment]
Hi,
understand .. can you add those ones?:
`erd
edo
lend
iota
gbp
eosup
sushidown
1inch`
they are listed on coinmarketcap

best regards

**Comment by alexandrebouttier** [comment]
I just added the following icons  , erd edo lend iota gbp eosup sushidown 1inch
